Enable the magic test suite

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,15 +5,15 @@ python: 2.7
 
 branches:
   only:
-  - master
+    - master
 
 cache:
   yarn: true
   directories:
     - "${HOME}/virtualenv/python$(python -c 'import platform; print(platform.python_version())')"
-    - "$NODE_DIR"
+    - '$NODE_DIR'
     - node_modules
-    - "${HOME}/google-cloud-sdk"
+    - '${HOME}/google-cloud-sdk'
 
 addons:
   apt:
@@ -49,11 +49,11 @@ after_failure:
 
 after_script:
   - |
-      coverage_files=$(ls .artifacts/*coverage.xml || true)
-      if [[ -n "$coverage_files" || -f .artifacts/coverage/cobertura-coverage.xml ]]; then
-        pip install -U codecov
-        codecov -e TEST_SUITE
-      fi
+    coverage_files=$(ls .artifacts/*coverage.xml || true)
+    if [[ -n "$coverage_files" || -f .artifacts/coverage/cobertura-coverage.xml ]]; then
+      pip install -U codecov
+      codecov -e TEST_SUITE
+    fi
   - ./bin/yarn global add @zeus-ci/cli
   - zeus upload -t "text/xml+xunit" .artifacts/*junit.xml
   - zeus upload -t "text/xml+coverage" .artifacts/*coverage.xml
@@ -64,25 +64,25 @@ after_script:
   - zeus upload -t "application/webpack-stats+json" .artifacts/*webpack-stats.json
   # Trigger a build for the `git` image on docker-sentry
   - >
-      curl -s -X POST
-      -H "Content-Type: application/json"
-      -H "Accept: application/json"
-      -H "Travis-API-Version: 3"
-      -H "Authorization: token $TRAVIS_TOKEN"
-      -d '{
-        "request": {
-          "branch": "master",
-          "config": {
-            "env": {
-              "matrix": [
-                "VERSION=git"
-              ]
-            }
-          },
-          "message": "Build for getsentry/sentry@'"$TRAVIS_COMMIT"'"
-        }
-      }'
-      https://api.travis-ci.org/repo/getsentry%2Fdocker-sentry/requests
+    curl -s -X POST
+    -H "Content-Type: application/json"
+    -H "Accept: application/json"
+    -H "Travis-API-Version: 3"
+    -H "Authorization: token $TRAVIS_TOKEN"
+    -d '{
+      "request": {
+        "branch": "master",
+        "config": {
+          "env": {
+            "matrix": [
+              "VERSION=git"
+            ]
+          }
+        },
+        "message": "Build for getsentry/sentry@'"$TRAVIS_COMMIT"'"
+      }
+    }'
+    https://api.travis-ci.org/repo/getsentry%2Fdocker-sentry/requests
 
 base_postgres: &postgres_default
   python: 2.7
@@ -124,135 +124,128 @@ base_acceptance: &acceptance_default
   before_script:
     - psql -c 'create database sentry;' -U postgres
 
-
 # each job in the matrix inherits `env/global` and uses everything above,
 # but custom `services`, `before_install`, `install`, and `before_script` directives
 # may be defined to define and setup individual job environments with more precision.
 matrix:
   fast_finish: true
   include:
-    # Lint python and javascript together
-    - python: 2.7
-      name: 'Linter'
-      env: TEST_SUITE=lint
-      install:
-        - SENTRY_LIGHT_BUILD=1 pip install -U -e ".[dev,tests,optional]"
-        - find "$NODE_DIR" -type d -empty -delete
-        - nvm install
-        - ./bin/yarn install --pure-lockfile
-
-    - <<: *postgres_default
-      name: 'Backend [Postgres] (1/2)'
-      env: TEST_SUITE=postgres DB=postgres TOTAL_TEST_GROUPS=2 TEST_GROUP=0
-    - <<: *postgres_default
-      name: 'Backend [Postgres] (2/2)'
-      env: TEST_SUITE=postgres DB=postgres TOTAL_TEST_GROUPS=2 TEST_GROUP=1
-
-    - python: 2.7
-      name: 'Backend [Riak]'
-      env: TEST_SUITE=riak DB=postgres
-      services:
-        - memcached
-        - redis-server
-        - postgresql
-        - riak
-      install:
-        - python setup.py install_egg_info
-        - pip install -U -e ".[dev,tests,optional]"
-      before_script:
-        - psql -c 'create database sentry;' -U postgres
-      before_install:
-        - docker run -d --network host --name clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:18.14.9
-        - docker run -d --network host --name snuba --env SNUBA_SETTINGS=test --env CLICKHOUSE_SERVER=localhost:9000 getsentry/snuba
-        - docker ps -a
-
     - <<: *acceptance_default
-      name: 'Acceptance'
-      env: TEST_SUITE=acceptance USE_SNUBA=1
+      name: 'MAGIC'
+      env: TEST_SUITE=magic USE_SNUBA=1
 
-    - python: 2.7
-      name: 'Frontend'
-      env: TEST_SUITE=js
-      before_install:
-        - find "$NODE_DIR" -type d -empty -delete
-        - nvm install
-      install:
-        - ./bin/yarn install --pure-lockfile
-
-    - python: 2.7
-      name: 'Command Line'
-      env: TEST_SUITE=cli
-      services:
-        - postgresql
-        - redis-server
-      install:
-        - python setup.py install_egg_info
-        - pip install -U -e .
-      before_script:
-        - psql -c 'create database sentry;' -U postgres
-
-    - python: 2.7
-      name: 'Distribution build'
-      env: TEST_SUITE=dist
-      before_install:
-        - find "$NODE_DIR" -type d -empty -delete
-        - nvm install
-
-    - <<: *postgres_default
-      name: 'Symbolicator Integration'
-      env: TEST_SUITE=symbolicator
-      before_install:
-        - docker run -d --network host --name clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:18.14.9
-        - docker run -d --network host --name snuba --env SNUBA_SETTINGS=test --env CLICKHOUSE_SERVER=localhost:9000 getsentry/snuba
-        - docker run -d --network host --name symbolicator us.gcr.io/sentryio/symbolicator:latest run
-        - docker ps -a
-
-    # snuba in testing
-    - python: 2.7
-      name: 'Snuba Integration'
-      env: TEST_SUITE=snuba USE_SNUBA=1 SENTRY_ZOOKEEPER_HOSTS=localhost:2181 SENTRY_KAFKA_HOSTS=localhost:9092
-      services:
-        - docker
-        - memcached
-        - redis-server
-        - postgresql
-      before_install:
-        - docker run -d --network host --name zookeeper -e ZOOKEEPER_CLIENT_PORT=2181 confluentinc/cp-zookeeper:4.1.0
-        - docker run -d --network host --name kafka -e KAFKA_ZOOKEEPER_CONNECT=localhost:2181 -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 confluentinc/cp-kafka:4.1.0
-        - docker run -d --network host --name clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:18.14.9
-        - docker run -d --network host --name snuba --env SNUBA_SETTINGS=test --env CLICKHOUSE_SERVER=localhost:9000 getsentry/snuba
-        - docker ps -a
-      install:
-        - python setup.py install_egg_info
-        - pip install -U -e ".[dev,tests,optional]"
-        - pip install confluent-kafka
-      before_script:
-        - psql -c 'create database sentry;' -U postgres
-
-    # Deploy 'storybook' (component & style guide) - allowed to fail
-    - language: node_js
-      name: 'Storybook Deploy'
-      env: STORYBOOK_BUILD=1
-      before_install:
-        # Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
-        - openssl aes-256-cbc -K $encrypted_020be61ef175_key -iv $encrypted_020be61ef175_iv -in .travis/storybook-credentials.tar.gz.enc -out credentials.tar.gz -d
-        # If the SDK is not already cached, download it and unpack it
-        - if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash; fi
-        - tar -xzf credentials.tar.gz
-        # Use the decrypted service account credentials to authenticate the command line tool
-        - gcloud auth activate-service-account --key-file client-secret.json
-      install:
-        - ./bin/yarn install --pure-lockfile
-        - gcloud version
-      script: bash .travis/deploy-storybook.sh
-      after_success: skip
-      after_failure: skip
-
-# jobs are defined in matrix/include
-# to specify which jobs are allowed to fail, match the env exactly in matrix/allow_failures
-  allow_failures:
-    - language: node_js
-      env: STORYBOOK_BUILD=1
+  #   # Lint python and javascript together
+  #   - python: 2.7
+  #     name: 'Linter'
+  #     env: TEST_SUITE=lint
+  #     install:
+  #       - SENTRY_LIGHT_BUILD=1 pip install -U -e ".[dev,tests,optional]"
+  #       - find "$NODE_DIR" -type d -empty -delete
+  #       - nvm install
+  #       - ./bin/yarn install --pure-lockfile
+  #   - <<: *postgres_default
+  #     name: 'Backend [Postgres] (1/2)'
+  #     env: TEST_SUITE=postgres DB=postgres TOTAL_TEST_GROUPS=2 TEST_GROUP=0
+  #   - <<: *postgres_default
+  #     name: 'Backend [Postgres] (2/2)'
+  #     env: TEST_SUITE=postgres DB=postgres TOTAL_TEST_GROUPS=2 TEST_GROUP=1
+  #   - python: 2.7
+  #     name: 'Backend [Riak]'
+  #     env: TEST_SUITE=riak DB=postgres
+  #     services:
+  #       - memcached
+  #       - redis-server
+  #       - postgresql
+  #       - riak
+  #     install:
+  #       - python setup.py install_egg_info
+  #       - pip install -U -e ".[dev,tests,optional]"
+  #     before_script:
+  #       - psql -c 'create database sentry;' -U postgres
+  #     before_install:
+  #       - docker run -d --network host --name clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:18.14.9
+  #       - docker run -d --network host --name snuba --env SNUBA_SETTINGS=test --env CLICKHOUSE_SERVER=localhost:9000 getsentry/snuba
+  #       - docker ps -a
+  #   - <<: *acceptance_default
+  #     name: 'Acceptance'
+  #     env: TEST_SUITE=acceptance USE_SNUBA=1
+  #   - python: 2.7
+  #     name: 'Frontend'
+  #     env: TEST_SUITE=js
+  #     before_install:
+  #       - find "$NODE_DIR" -type d -empty -delete
+  #       - nvm install
+  #     install:
+  #       - ./bin/yarn install --pure-lockfile
+  #   - python: 2.7
+  #     name: 'Command Line'
+  #     env: TEST_SUITE=cli
+  #     services:
+  #       - postgresql
+  #       - redis-server
+  #     install:
+  #       - python setup.py install_egg_info
+  #       - pip install -U -e .
+  #     before_script:
+  #       - psql -c 'create database sentry;' -U postgres
+  #   - python: 2.7
+  #     name: 'Distribution build'
+  #     env: TEST_SUITE=dist
+  #     before_install:
+  #       - find "$NODE_DIR" -type d -empty -delete
+  #       - nvm install
+  #   - <<: *postgres_default
+  #     name: 'Symbolicator Integration'
+  #     env: TEST_SUITE=symbolicator
+  #     before_install:
+  #       - docker run -d --network host --name clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:18.14.9
+  #       - docker run -d --network host --name snuba --env SNUBA_SETTINGS=test --env CLICKHOUSE_SERVER=localhost:9000 getsentry/snuba
+  #       - docker run -d --network host --name symbolicator us.gcr.io/sentryio/symbolicator:latest run
+  #       - docker ps -a
+  #   # snuba in testing
+  #   - python: 2.7
+  #     name: 'Snuba Integration'
+  #     env: TEST_SUITE=snuba USE_SNUBA=1 SENTRY_ZOOKEEPER_HOSTS=localhost:2181 SENTRY_KAFKA_HOSTS=localhost:9092
+  #     services:
+  #       - docker
+  #       - memcached
+  #       - redis-server
+  #       - postgresql
+  #     before_install:
+  #       - docker run -d --network host --name zookeeper -e ZOOKEEPER_CLIENT_PORT=2181 confluentinc/cp-zookeeper:4.1.0
+  #       - docker run -d --network host --name kafka -e KAFKA_ZOOKEEPER_CONNECT=localhost:2181 -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 confluentinc/cp-kafka:4.1.0
+  #       - docker run -d --network host --name clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:18.14.9
+  #       - docker run -d --network host --name snuba --env SNUBA_SETTINGS=test --env CLICKHOUSE_SERVER=localhost:9000 getsentry/snuba
+  #       - docker ps -a
+  #     install:
+  #       - python setup.py install_egg_info
+  #       - pip install -U -e ".[dev,tests,optional]"
+  #       - pip install confluent-kafka
+  #     before_script:
+  #       - psql -c 'create database sentry;' -U postgres
+  #   # Deploy 'storybook' (component & style guide) - allowed to fail
+  #   - language: node_js
+  #     name: 'Storybook Deploy'
+  #     env: STORYBOOK_BUILD=1
+  #     before_install:
+  #       # Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
+  #       - openssl aes-256-cbc -K $encrypted_020be61ef175_key -iv $encrypted_020be61ef175_iv -in .travis/storybook-credentials.tar.gz.enc -out credentials.tar.gz -d
+  #       # If the SDK is not already cached, download it and unpack it
+  #       - if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash; fi
+  #       - tar -xzf credentials.tar.gz
+  #       # Use the decrypted service account credentials to authenticate the command line tool
+  #       - gcloud auth activate-service-account --key-file client-secret.json
+  #     install:
+  #       - ./bin/yarn install --pure-lockfile
+  #       - gcloud version
+  #     script: bash .travis/deploy-storybook.sh
+  #     after_success: skip
+  #     after_failure: skip
+  # # jobs are defined in matrix/include
+  # # to specify which jobs are allowed to fail, match the env exactly in matrix/allow_failures
+  # allow_failures:
+  #   - language: node_js
+  #     env: STORYBOOK_BUILD=1
 
 notifications:
   webhooks:
