try better bash-fu

diff --git a/docker/cloudbuild.yaml b/docker/cloudbuild.yaml
--- a/docker/cloudbuild.yaml
+++ b/docker/cloudbuild.yaml
@@ -36,7 +36,12 @@ steps:
     # The following trick is from https://stackoverflow.com/a/52400857/90297 with great gratuity
     echo '{"version": "3.4", "networks":{"default":{"external":{"name":"cloudbuild"}}}}' > docker-compose.override.yml
     ./install.sh
-    ./test.sh || docker-compose logs nginx web relay && exit -1
+    if ! ./test.sh; then
+      echo "Test failed.";
+      docker-compose ps;
+      docker-compose logs nginx web relay;
+      exit -1;
+    fi
   timeout: 450s
 - name: 'gcr.io/cloud-builders/docker'
   secretEnv: ['DOCKER_PASSWORD']
