hardcode MATRIX_INSTANCE_TOTAL

diff --git a/.github/actions/setup-sentry/action.yml b/.github/actions/setup-sentry/action.yml
--- a/.github/actions/setup-sentry/action.yml
+++ b/.github/actions/setup-sentry/action.yml
@@ -54,6 +54,9 @@ outputs:
   matrix-instance-number:
     description: "The matrix instance number (starting at 1)"
     value: ${{ steps.config.outputs.matrix-instance-number }}
+  matrix-instance-total:
+    description: "Reexport of MATRIX_INSTANCE_TOTAL."
+    value: ${{ steps.config.outputs.matrix-instance-total }}
 
 runs:
   using: "composite"
@@ -63,7 +66,10 @@ runs:
       env:
         NEED_KAFKA: ${{ inputs.kafka }}
         MATRIX_INSTANCE: ${{ matrix.instance }}
-        MATRIX_INSTANCE_TOTAL: ${{ strategy.job-total }}
+        # XXX: We should be using something like len(strategy.matrix.instance) (not possible atm)
+        # If you have other things like python-version: [foo, bar, baz] then the sharding logic
+        # isn't right because job-total will be 3x larger and you'd never run 2/3 of the tests.
+        # MATRIX_INSTANCE_TOTAL: ${{ strategy.job-total }}
       run: |
         # Only set `MIGRATIONS_TEST_MIGRATE` if it is not already set (or if it's an empty string)
         if [ -z $MIGRATIONS_TEST_MIGRATE ]; then
@@ -81,11 +87,17 @@ runs:
         ### pytest-sentry configuration ###
         echo "PYTEST_SENTRY_DSN=https://6fd5cfea2d4d46b182ad214ac7810508@sentry.io/2423079" >> $GITHUB_ENV
         echo "PYTEST_ADDOPTS=--reruns 5" >> $GITHUB_ENV
+
         # this handles pytest test sharding
         if [ "$MATRIX_INSTANCE" ]; then
+          if [ "$MATRIX_INSTANCE_TOTAL" ] then;
+            echo "MATRIX_INSTANCE_TOTAL is required."
+            exit 1
+          fi
           echo "TEST_GROUP=$MATRIX_INSTANCE" >> $GITHUB_ENV
           echo "TOTAL_TEST_GROUPS=$MATRIX_INSTANCE_TOTAL" >> $GITHUB_ENV
         fi
+
         # This records failures on master to sentry in order to detect flakey tests, as it's
         # expected that people have failing tests on their PRs
         [ "$GITHUB_REF" = "refs/heads/master" ] && echo "PYTEST_SENTRY_ALWAYS_REPORT=1" >> $GITHUB_ENV || true
@@ -124,6 +136,7 @@ runs:
       run: |
         echo "::set-output name=yarn-cache-dir::$(yarn cache dir)"
         echo "::set-output name=matrix-instance-number::$(($MATRIX_INSTANCE+1))"
+        echo "::set-output name=matrix-instance-total::$(($MATRIX_INSTANCE_TOTAL))"
         echo "::set-output name=acceptance-dir::.artifacts/visual-snapshots/acceptance"
 
     - name: Install python dependencies
