venv_name for consistency, also VENV seems clobberable

diff --git a/scripts/bootstrap-py3-venv b/scripts/bootstrap-py3-venv
--- a/scripts/bootstrap-py3-venv
+++ b/scripts/bootstrap-py3-venv
@@ -25,9 +25,9 @@ command -v direnv >/dev/null || {
 gitroot="$(git rev-parse --show-toplevel)"
 cd "$gitroot"
 # Be careful changing this as there's a rm -rf later in the script
-export VENV="$PWD/.venv"
+export venv_name="${PWD}/.venv"
 
-if [[ -f ${VENV}/bin/activate ]]; then
+if [[ -f "${venv_name}/bin/activate" ]]; then
     echo "You seem to have a virtualenv already. This script is meant to start one from scratch. Continue (y/N)?"
     read resp
     case "$resp" in
@@ -37,7 +37,7 @@ if [[ -f ${VENV}/bin/activate ]]; then
 fi
 
 deactivate 2>/dev/null || true
-rm -rf "$VENV"
+rm -rf "$venv_name"
 
 major=$(python -c "import sys; print(sys.version_info[0])")
 minor=$(python -c "import sys; print(sys.version_info[1])")
@@ -47,8 +47,8 @@ fi
 
 python3 -m pip install -U pip           || { echo "bootstrap failed!"; return 1; }
 python3 -m pip install -U virtualenv    || { echo "bootstrap failed!"; return 1; }
-python3 -m virtualenv "${VENV}"           || { echo "bootstrap failed!"; return 1; }
-source "${VENV}"/bin/activate             || { echo "bootstrap failed!"; return 1; }
+python3 -m virtualenv "${venv_name}"    || { echo "bootstrap failed!"; return 1; }
+source "${venv_name}/bin/activate"      || { echo "bootstrap failed!"; return 1; }
 make setup-git                          || { echo "bootstrap failed!"; return 1; }
 make install-py-dev                     || { echo "bootstrap failed!"; return 1; }
 deactivate                              || { echo "bootstrap failed!"; return 1; }
