feat(dev_env): Dev env bootstrap support for two Python versions
This change adds supports for bootstrapping two different Python versions.
Python 3.8.10 will be used for Apple M1 since we're targetting Python 3.8 for Sentry's
next Python version and it is the first one that supports Apple's M1 chipset.

diff --git a/scripts/bootstrap-py3-venv b/scripts/bootstrap-py3-venv
--- a/scripts/bootstrap-py3-venv
+++ b/scripts/bootstrap-py3-venv
@@ -11,6 +11,11 @@
 # trap "echo 'bootstrap FAILED.' && trap - ERR && return" ERR
 
 # So just going to sprinkle returns everywhere.
+SCRIPTS_DIR="$(
+    cd "$(dirname "${BASH_SOURCE[0]}")"
+    pwd -P
+)"
+source "${SCRIPTS_DIR}/lib.sh"
 
 command -v pyenv >/dev/null || {
     echo "You need to install pyenv. https://develop.sentry.dev/environment/#python"
@@ -24,7 +29,7 @@ command -v direnv >/dev/null || {
 
 gitroot="$(git rev-parse --show-toplevel)"
 cd "$gitroot"
-export venv_name="${PWD}/.venv"
+venv_name="${PWD}/.venv"
 
 if [[ -f "${venv_name}/bin/activate" ]]; then
     prompt_text="You have an existing virtualenv. This script will OVERWRITE it. Continue (y/N)?"
@@ -42,7 +47,7 @@ rm -rf "$venv_name"
 
 # XXX: You'll also need to temporarily pyenv local "$SENTRY_PYTHON_VERSION"
 #      and then revert changes to the .python-version after bootstrap finishes.
-if [[ -z "$SENTRY_PYTHON_VERSION" ]] && ! [[ "$(python3 -V 2>&1)" = "Python $(grep "3.6" .python-version)" ]]; then
+if [[ -z "$SENTRY_PYTHON_VERSION" ]] && ! query-valid-python-versions; then
     echo "Your python3 version isn't as expected. Please run: make setup-pyenv"
     return 1
 fi
@@ -50,7 +55,7 @@ fi
 python3 -m pip install -U pip           || { echo "bootstrap failed!"; return 1; }
 python3 -m venv "${venv_name}"          || { echo "bootstrap failed!"; return 1; }
 source "${venv_name}/bin/activate"      || { echo "bootstrap failed!"; return 1; }
-python3 -m pip install -U pip           || { echo "bootstrap failed!"; return 1; }
+python3 -m pip install -U pip wheel     || { echo "bootstrap failed!"; return 1; }
 make setup-git                          || { echo "bootstrap failed!"; return 1; }
 make install-py-dev                     || { echo "bootstrap failed!"; return 1; }
 deactivate                              || { echo "bootstrap failed!"; return 1; }
