build(feat): Make Python 3 the default development environment
* Python 3 will get installed under `.venv` instead of `.venv3`
  * Python 2 will temporarily be allowed to be installed under `.venv2`
* Dropping the need for SENTRY_PYTHON3
  * Temporarily adding SENTRY_PYTHON2 to support Python 2

diff --git a/scripts/bootstrap-py2-venv b/scripts/bootstrap-py2-venv
--- a/scripts/bootstrap-py2-venv
+++ b/scripts/bootstrap-py2-venv
@@ -22,12 +22,14 @@ command -v direnv >/dev/null || {
     return 1
 }
 
-unset SENTRY_PYTHON3
+export SENTRY_PYTHON2=1
 
 gitroot="$(git rev-parse --show-toplevel)"
 cd "$gitroot"
+# Be careful changing this as there's a rm -rf later in the script
+export VENV=`pwd`/.venv2
 
-if [[ -f .venv/bin/activate ]]; then
+if [[ -f ${VENV}/bin/activate ]]; then
     echo "You seem to have a virtualenv already. This script is meant to start one from scratch. Continue (y/N)?"
     read resp
     case "$resp" in
@@ -37,7 +39,7 @@ if [[ -f .venv/bin/activate ]]; then
 fi
 
 deactivate 2>/dev/null || true
-rm -rf .venv/
+rm -rf ${VENV}/
 
 if ! [[ "$(python2.7 -V 2>&1)" = "Python $(awk -v ORS='' 'FNR == 1' .python-version)" ]]; then
     abort "Your python2.7 version isn't as expected. Please run: make setup-pyenv"
@@ -45,8 +47,8 @@ fi
 
 python2.7 -m pip install -U pip         || { echo "bootstrap failed!"; return 1; }
 python2.7 -m pip install -U virtualenv  || { echo "bootstrap failed!"; return 1; }
-python2.7 -m virtualenv .venv           || { echo "bootstrap failed!"; return 1; }
-source .venv/bin/activate               || { echo "bootstrap failed!"; return 1; }
+python2.7 -m virtualenv ${VENV}         || { echo "bootstrap failed!"; return 1; }
+source ${VENV}/bin/activate             || { echo "bootstrap failed!"; return 1; }
 make setup-git                          || { echo "bootstrap failed!"; return 1; }
 make install-py-dev                     || { echo "bootstrap failed!"; return 1; }
 deactivate                              || { echo "bootstrap failed!"; return 1; }
diff --git a/scripts/bootstrap-py3-venv b/scripts/bootstrap-py3-venv
--- a/scripts/bootstrap-py3-venv
+++ b/scripts/bootstrap-py3-venv
@@ -22,12 +22,12 @@ command -v direnv >/dev/null || {
     return 1
 }
 
-export SENTRY_PYTHON3=1
-
 gitroot="$(git rev-parse --show-toplevel)"
 cd "$gitroot"
+# Be careful changing this as there's a rm -rf later in the script
+export VENV=`pwd`/.venv
 
-if [[ -f .venv3/bin/activate ]]; then
+if [[ -f ${VENV}/bin/activate ]]; then
     echo "You seem to have a virtualenv already. This script is meant to start one from scratch. Continue (y/N)?"
     read resp
     case "$resp" in
@@ -37,7 +37,7 @@ if [[ -f .venv3/bin/activate ]]; then
 fi
 
 deactivate 2>/dev/null || true
-rm -rf .venv3/
+rm -rf ${VENV}
 
 if ! [[ "$(python3 -V 2>&1)" = "Python $(awk -v ORS='' 'FNR == 2' .python-version)" ]]; then
     abort "Your python3 version isn't as expected. Please run: make setup-pyenv"
@@ -45,8 +45,8 @@ fi
 
 python3 -m pip install -U pip           || { echo "bootstrap failed!"; return 1; }
 python3 -m pip install -U virtualenv    || { echo "bootstrap failed!"; return 1; }
-python3 -m virtualenv .venv3            || { echo "bootstrap failed!"; return 1; }
-source .venv3/bin/activate              || { echo "bootstrap failed!"; return 1; }
+python3 -m virtualenv ${VENV}           || { echo "bootstrap failed!"; return 1; }
+source ${VENV}/bin/activate             || { echo "bootstrap failed!"; return 1; }
 make setup-git                          || { echo "bootstrap failed!"; return 1; }
 make install-py-dev                     || { echo "bootstrap failed!"; return 1; }
 deactivate                              || { echo "bootstrap failed!"; return 1; }
