small touchups

diff --git a/scripts/bootstrap-py2-venv b/scripts/bootstrap-py2-venv
--- a/scripts/bootstrap-py2-venv
+++ b/scripts/bootstrap-py2-venv
@@ -39,7 +39,7 @@ if [[ -f ${VENV}/bin/activate ]]; then
 fi
 
 deactivate 2>/dev/null || true
-rm -rf ${VENV}/
+rm -rf "${VENV}"/
 
 if ! [[ "$(python2.7 -V 2>&1)" = "Python $(grep "2.7" .python-version)" ]]; then
     abort "Your python2.7 version isn't as expected. Please run: make setup-pyenv"
@@ -47,8 +47,8 @@ fi
 
 python2.7 -m pip install -U pip         || { echo "bootstrap failed!"; return 1; }
 python2.7 -m pip install -U virtualenv  || { echo "bootstrap failed!"; return 1; }
-python2.7 -m virtualenv ${VENV}         || { echo "bootstrap failed!"; return 1; }
-source ${VENV}/bin/activate             || { echo "bootstrap failed!"; return 1; }
+python2.7 -m virtualenv "${VENV}"         || { echo "bootstrap failed!"; return 1; }
+source "${VENV}"/bin/activate             || { echo "bootstrap failed!"; return 1; }
 make setup-git                          || { echo "bootstrap failed!"; return 1; }
 make install-py-dev                     || { echo "bootstrap failed!"; return 1; }
 deactivate                              || { echo "bootstrap failed!"; return 1; }
diff --git a/scripts/bootstrap-py3-venv b/scripts/bootstrap-py3-venv
--- a/scripts/bootstrap-py3-venv
+++ b/scripts/bootstrap-py3-venv
@@ -37,18 +37,18 @@ if [[ -f ${VENV}/bin/activate ]]; then
 fi
 
 deactivate 2>/dev/null || true
-rm -rf ${VENV}
+rm -rf "$VENV"
 
-major=`python -c "import sys; print(sys.version_info[0])"`
-minor=`python -c "import sys; print(sys.version_info[1])"`
+major=$(python -c "import sys; print(sys.version_info[0])")
+minor=$(python -c "import sys; print(sys.version_info[1])")
 if ! [[ major -eq 3 && minor -ge 6 ]]; then
     abort "Your python3 version isn't as expected. Please run: make setup-pyenv"
 fi
 
 python3 -m pip install -U pip           || { echo "bootstrap failed!"; return 1; }
 python3 -m pip install -U virtualenv    || { echo "bootstrap failed!"; return 1; }
-python3 -m virtualenv ${VENV}           || { echo "bootstrap failed!"; return 1; }
-source ${VENV}/bin/activate             || { echo "bootstrap failed!"; return 1; }
+python3 -m virtualenv "${VENV}"           || { echo "bootstrap failed!"; return 1; }
+source "${VENV}"/bin/activate             || { echo "bootstrap failed!"; return 1; }
 make setup-git                          || { echo "bootstrap failed!"; return 1; }
 make install-py-dev                     || { echo "bootstrap failed!"; return 1; }
 deactivate                              || { echo "bootstrap failed!"; return 1; }
