dev: default to Python 3 (#22330)

diff --git a/scripts/bootstrap-py2-venv b/scripts/bootstrap-py2-venv
--- a/scripts/bootstrap-py2-venv
+++ b/scripts/bootstrap-py2-venv
@@ -22,12 +22,13 @@ command -v direnv >/dev/null || {
     return 1
 }
 
-unset SENTRY_PYTHON3
+export SENTRY_PYTHON2=1
 
 gitroot="$(git rev-parse --show-toplevel)"
 cd "$gitroot"
+export venv_name="${PWD}/.venv2"
 
-if [[ -f .venv/bin/activate ]]; then
+if [[ -f "${venv_name}/bin/activate" ]]; then
     echo "You seem to have a virtualenv already. This script is meant to start one from scratch. Continue (y/N)?"
     read resp
     case "$resp" in
@@ -37,16 +38,16 @@ if [[ -f .venv/bin/activate ]]; then
 fi
 
 deactivate 2>/dev/null || true
-rm -rf .venv/
+rm -rf "$venv_name"
 
-if ! [[ "$(python2.7 -V 2>&1)" = "Python $(awk -v ORS='' 'FNR == 1' .python-version)" ]]; then
+if ! [[ "$(python2.7 -V 2>&1)" = "Python $(grep "2.7" .python-version)" ]]; then
     abort "Your python2.7 version isn't as expected. Please run: make setup-pyenv"
 fi
 
 python2.7 -m pip install -U pip         || { echo "bootstrap failed!"; return 1; }
 python2.7 -m pip install -U virtualenv  || { echo "bootstrap failed!"; return 1; }
-python2.7 -m virtualenv .venv           || { echo "bootstrap failed!"; return 1; }
-source .venv/bin/activate               || { echo "bootstrap failed!"; return 1; }
+python2.7 -m virtualenv "${venv_name}"  || { echo "bootstrap failed!"; return 1; }
+source "${venv_name}/bin/activate"      || { echo "bootstrap failed!"; return 1; }
 make setup-git                          || { echo "bootstrap failed!"; return 1; }
 make install-py-dev                     || { echo "bootstrap failed!"; return 1; }
 deactivate                              || { echo "bootstrap failed!"; return 1; }
