feat(ci): Collector jobs should fail on dependent job failure
In an attempt to reduce required checks (#33408), we merged jobs into less workflows and used collector jobs that would be marked as required (#33455).

Unfortunately, if one of the jobs we depend on fails, the collector job would be marked as Skipped which satisfies the Github required check. This allowed for the introduction of a regression on a PR earlier on the week (see https://github.com/getsentry/sentry/runs/6064646921?check_suite_focus=true).

This change makes each required check have a step which verifies the result of all dependent jobs. If any of them fails, the collector job fails as well.

diff --git a/.github/workflows/acceptance.yml b/.github/workflows/acceptance.yml
--- a/.github/workflows/acceptance.yml
+++ b/.github/workflows/acceptance.yml
@@ -307,15 +307,23 @@ jobs:
     # workflows that generate artifacts succeed
     needs: [acceptance, frontend, chartcuterie]
     name: triggers visual snapshot
-    # Do not execute on forks or on master
-    if: github.repository == 'getsentry/sentry' && github.ref != 'refs/heads/master'
+    # This is necessary since a failed/skipped dependent job would cause this job to be skipped
+    if: always()
     runs-on: ubuntu-20.04
     timeout-minutes: 20
 
     steps:
+      # If any jobs we depend on fail, we will fail since this checks triggers Visual Snapshots which is a required check
+      - name: Check for failures
+        if: contains(needs.*.result, 'failure')
+        run: |
+          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
+
       - name: Diff snapshots
         id: visual-snapshots-diff
         uses: getsentry/action-visual-snapshot@v2
+        # Do not execute on forks or on master. Forks are handled in visual-diff.yml
+        if: github.repository == 'getsentry/sentry' && github.ref != 'refs/heads/master'
         with:
           api-token: ${{ secrets.VISUAL_SNAPSHOT_SECRET }}
           gcs-bucket: 'sentry-visual-snapshots'
