restore

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -38,6 +38,29 @@ jobs:
           token: ${{ github.token }}
           filters: .github/file-filters.yml
 
+  api-docs:
+    if: needs.files-changed.outputs.api_docs == 'true'
+    needs: files-changed
+    name: api docs test
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
+
+      - uses: getsentry/action-setup-volta@54775a59c41065f54ecc76d1dd5f2cdc7a1550cb # v1.1.0
+
+      - name: Setup sentry python env
+        uses: ./.github/actions/setup-sentry
+        id: setup
+        with:
+          snuba: true
+
+      - name: Run API docs tests
+        # install ts-node for ts build scripts to execute properly without potentially installing
+        # conflicting deps when running scripts locally
+        # see: https://github.com/getsentry/sentry/pull/32328/files
+        run: |
+          yarn add ts-node && make test-api-docs
+
   backend-test:
     if: needs.files-changed.outputs.backend == 'true'
     needs: files-changed
@@ -89,3 +112,197 @@ jobs:
         uses: ./.github/actions/artifacts
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
+
+  backend-migration-tests:
+    if: needs.files-changed.outputs.backend == 'true'
+    needs: files-changed
+    name: backend migration tests
+    runs-on: ubuntu-20.04
+    timeout-minutes: 30
+    strategy:
+      matrix:
+        pg-version: ['14']
+
+    steps:
+      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
+        with:
+          # Avoid codecov error message related to SHA resolution:
+          # https://github.com/codecov/codecov-bash/blob/7100762afbc822b91806a6574658129fe0d23a7d/codecov#L891
+          fetch-depth: '2'
+
+      - name: Setup sentry env
+        uses: ./.github/actions/setup-sentry
+        id: setup
+        with:
+          snuba: true
+          pg-version: ${{ matrix.pg-version }}
+
+      - name: run tests
+        run: |
+          MIGRATIONS_TEST_MIGRATE=1 PYTEST_ADDOPTS="$PYTEST_ADDOPTS -m migrations" make test-python-ci
+
+      # Upload coverage data even if running the tests step fails since
+      # it reduces large coverage fluctuations
+      - name: Handle artifacts
+        if: ${{ always() }}
+        uses: ./.github/actions/artifacts
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+
+  cli:
+    if: needs.files-changed.outputs.backend == 'true'
+    needs: files-changed
+    name: cli test
+    runs-on: ubuntu-20.04
+    timeout-minutes: 10
+    strategy:
+      matrix:
+        pg-version: ['14']
+    steps:
+      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
+
+      - name: Setup sentry env
+        uses: ./.github/actions/setup-sentry
+        id: setup
+        with:
+          pg-version: ${{ matrix.pg-version }}
+
+      - name: Run test
+        run: |
+          make test-cli
+
+      # Upload coverage data even if running the tests step fails since
+      # it reduces large coverage fluctuations
+      - name: Handle artifacts
+        if: ${{ always() }}
+        uses: ./.github/actions/artifacts
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+
+  requirements:
+    if: needs.files-changed.outputs.backend_dependencies == 'true'
+    needs: files-changed
+    name: requirements check
+    runs-on: ubuntu-20.04
+    timeout-minutes: 3
+    steps:
+      - uses: getsentry/action-github-app-token@97c9e23528286821f97fba885c1b1123284b29cc # v2.0.0
+        id: token
+        continue-on-error: true
+        with:
+          app_id: ${{ vars.SENTRY_INTERNAL_APP_ID }}
+          private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}
+      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
+      - uses: getsentry/action-setup-venv@9e3bbae3836b1b6f129955bf55a19e1d99a61c67 # v1.0.5
+        with:
+          python-version: 3.8.16
+          cache-depedency: requirements-dev-frozen.txt
+          install-cmd: pip install -q --constraint requirements-dev-frozen.txt pip-tools
+      - name: check requirements
+        run: |
+          python -S -m tools.freeze_requirements
+          if ! git diff --exit-code; then
+            echo $'\n\nrun `make freeze-requirements` locally to update requirements'
+            exit 1
+          fi
+      - name: apply any requirements changes
+        if: steps.token.outcome == 'success' && github.ref != 'refs/heads/master' && always()
+        uses: getsentry/action-github-commit@748c31dd78cffe76f51bef49a0be856b6effeda7 # v1.1.0
+        with:
+          github-token: ${{ steps.token.outputs.token }}
+          message: ':snowflake: re-freeze requirements'
+
+  migration:
+    if: needs.files-changed.outputs.migration_lockfile == 'true'
+    needs: files-changed
+    name: check migration
+    runs-on: ubuntu-20.04
+    strategy:
+      matrix:
+        pg-version: ['14']
+
+    steps:
+      - name: Checkout sentry
+        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
+
+      - name: Setup sentry env
+        uses: ./.github/actions/setup-sentry
+        id: setup
+        with:
+          pg-version: ${{ matrix.pg-version }}
+
+      - name: Migration & lockfile checks
+        env:
+          SENTRY_LOG_LEVEL: ERROR
+          PGPASSWORD: postgres
+        run: |
+          ./.github/workflows/scripts/migration-check.sh
+
+  typing:
+    if: needs.files-changed.outputs.backend == 'true'
+    needs: files-changed
+    name: backend typing
+    runs-on: ubuntu-20.04
+    timeout-minutes: 20
+    steps:
+      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
+
+      - uses: getsentry/action-setup-venv@9e3bbae3836b1b6f129955bf55a19e1d99a61c67 # v1.0.5
+        with:
+          python-version: 3.8.16
+          cache-dependency-path: requirements-dev-frozen.txt
+          install-cmd: pip install -r requirements-dev-frozen.txt
+
+      - name: setup sentry (lite)
+        run: |
+          SENTRY_LIGHT_BUILD=1 pip install --no-deps -e .
+          sentry init
+
+      - run: mypy
+        id: run
+
+      - uses: getsentry/action-github-app-token@97c9e23528286821f97fba885c1b1123284b29cc # v2.0.0
+        id: token
+        continue-on-error: true
+        with:
+          app_id: ${{ vars.SENTRY_INTERNAL_APP_ID }}
+          private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}
+
+      # only if `mypy` succeeds should we try and trim the blocklist
+      - run: |
+          python3 -m tools.mypy_helpers.make_module_ignores
+          git diff --exit-code
+
+      - name: apply blocklist changes
+        if: steps.token.outcome == 'success' && steps.run.outcome == 'success' && github.ref != 'refs/heads/master' && always()
+        uses: getsentry/action-github-commit@748c31dd78cffe76f51bef49a0be856b6effeda7 # v1.1.0
+        with:
+          github-token: ${{ steps.token.outputs.token }}
+          message: ':knife: regenerate mypy module blocklist'
+
+  # This check runs once all dependent jobs have passed
+  # It symbolizes that all required Backend checks have succesfully passed (Or skipped)
+  # This step is the only required backend check
+  backend-required-check:
+    needs:
+      [
+        api-docs,
+        backend-test,
+        backend-migration-tests,
+        cli,
+        files-changed,
+        requirements,
+        migration,
+        typing,
+      ]
+    name: Backend
+    # This is necessary since a failed/skipped dependent job would cause this job to be skipped
+    if: always()
+    runs-on: ubuntu-20.04
+    steps:
+      # If any jobs we depend on fail, we will fail since this is a required check
+      # NOTE: A timeout is considered a failure
+      - name: Check for failures
+        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: |
+          echo "One of the dependent jobs have failed. You may need to re-run it." && exit 1
