Adjust exit code

diff --git a/.github/workflows/check-if-migration-is-required.yml b/.github/workflows/check-if-migration-is-required.yml
--- a/.github/workflows/check-if-migration-is-required.yml
+++ b/.github/workflows/check-if-migration-is-required.yml
@@ -46,5 +46,9 @@ jobs:
           PGPASSWORD: postgres
         run: |
           # Below will exit with non-zero status if model changes are missing migrations
-          sentry django makemigrations -n ci_test --check --dry-run --no-input || (echo '::error::Error: Migration required -- to generate a migration, run `sentry django makemigrations -n <some_name>`' && exit 1)
-          sentry django makemigrations --check || echo >&2 "::error::Error: You have not commited the migration_lockfile.txt"
+          sentry django makemigrations --check --dry-run --no-input
+          if [ "$?" == 1 ]; then
+            echo >&2'::error::Error: Migration required -- to generate a migration, run `sentry django makemigrations -n <some_name>`' && exit 1
+          else:
+            echo >&2 "::error::Error: You have not commited the migration_lockfile.txt"
+          fi
