Clean up

diff --git a/.github/workflows/check-if-migration-is-required.yml b/.github/workflows/check-if-migration-is-required.yml
--- a/.github/workflows/check-if-migration-is-required.yml
+++ b/.github/workflows/check-if-migration-is-required.yml
@@ -48,7 +48,7 @@ jobs:
           # Below will exit with non-zero status if model changes are missing migrations
           sentry django makemigrations --check --dry-run --no-input
           if [ "$?" == 1 ]; then
-            echo >&2'::error::Error: Migration required -- to generate a migration, run `sentry django makemigrations -n <some_name>`' && exit 1
+            echo >&2 "::error::Error: Migration required -- to generate a migration, run `sentry django makemigrations -n <some_name>`" && exit 1
           else:
-            echo >&2 "::error::Error: You have not commited the migration_lockfile.txt"
+            echo >&2 "::error::Error: You have not commited the migration_lockfile.txt" && exit 1
           fi
