fix(ci): Fix migration checks
This fixes a regression introduced in #25499.

When `sentry django makemigrations --check` does not exit with exit code zero, the
conditional checks in the next line will not be evaluated.

This captures the stdout/stderr into a variable and the exit code into another one.

diff --git a/.github/workflows/check-if-migration-is-required.yml b/.github/workflows/check-if-migration-is-required.yml
--- a/.github/workflows/check-if-migration-is-required.yml
+++ b/.github/workflows/check-if-migration-is-required.yml
@@ -40,14 +40,16 @@ jobs:
         uses: ./.github/actions/setup-sentry
         id: setup
 
-      - name: Check if a migration is required
+      - name: Migration & lockfile checks
         env:
           SENTRY_LOG_LEVEL: ERROR
           PGPASSWORD: postgres
         run: |
-          # Below will exit with non-zero status if model changes are missing migrations
-          sentry django makemigrations --check --dry-run --no-input
-          if [ "$?" == 1 ]; then
+          # This will fail if a migration or the lockfile are missing in the PR
+          output=$((sentry django makemigrations --check --dry-run --no-input) 2>&1)
+          exit_code=$?
+          echo "$output"
+          if [ "$exit_code" == 1 ]; then
             echo >&2 "::error::Error: Migration required -- to generate a migration, run `sentry django makemigrations -n <some_name> && git add migrations_lockfile.txt`" && exit 1
           else:
             echo >&2 "::error::Error: Migration lockfile mismatch -- run `sentry django makemigrations -n <some_name> && git add migrations_lockfile.txt`" && exit 1
