error message

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -102,8 +102,4 @@ jobs:
           run: |
             # Below will exit with non-zero status if model changes are missing migrations
             sentry django makemigrations -n ci_test --check --dry-run --no-input
-
-        - name: Migration Required
-          if: ${{ failure() }}
-          run: |
-            echo "::error Error: Migration required -- to generate a migration, run `sentry django makemigrations -n <some_name>`"
+            rc=$?; echo '::error Error: Migration required -- to generate a migration, run `sentry django makemigrations -n <some_name>`'; return $rc
